<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; Prediction with Regression – Data Science for Political Science</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./09-Fairness.html" rel="next">
<link href="./07-Prediction.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9becf3fbc736aa3d8123452166bd44f5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./08-Regression.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Prediction with Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Data Science for Political Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course Notes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Description.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Description</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-CausalityI.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Causation with Experiments</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-Visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Causalityii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Causality with Non-Experimental Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-Loops.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Loops in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-Prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Prediction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-Regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Prediction with Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-Fairness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Fairness and Ethics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-Uncertainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Uncertainty</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-TextasData.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Text as Data</span></span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Section Contents</h2>
   
  <ul>
  <li><a href="#regression-in-the-wild." id="toc-regression-in-the-wild." class="nav-link active" data-scroll-target="#regression-in-the-wild."><span class="header-section-number">8.1</span> Regression in the wild.</a></li>
  <li><a href="#application-baseball-predictions" id="toc-application-baseball-predictions" class="nav-link" data-scroll-target="#application-baseball-predictions"><span class="header-section-number">8.2</span> Application: Baseball Predictions</a></li>
  <li><a href="#step-1-approach--regression-in-r" id="toc-step-1-approach--regression-in-r" class="nav-link" data-scroll-target="#step-1-approach--regression-in-r"><span class="header-section-number">8.3</span> Step 1: Approach- Regression in R</a>
  <ul>
  <li><a href="#visualizing-a-regression" id="toc-visualizing-a-regression" class="nav-link" data-scroll-target="#visualizing-a-regression"><span class="header-section-number">8.3.1</span> Visualizing a regression</a></li>
  <li><a href="#making-predictions-with-regression" id="toc-making-predictions-with-regression" class="nav-link" data-scroll-target="#making-predictions-with-regression"><span class="header-section-number">8.3.2</span> Making predictions with regression</a></li>
  </ul></li>
  <li><a href="#step-2-checking-accuracy-of-model" id="toc-step-2-checking-accuracy-of-model" class="nav-link" data-scroll-target="#step-2-checking-accuracy-of-model"><span class="header-section-number">8.4</span> Step 2: Checking accuracy of model</a>
  <ul>
  <li><a href="#root-mean-squared-error" id="toc-root-mean-squared-error" class="nav-link" data-scroll-target="#root-mean-squared-error"><span class="header-section-number">8.4.1</span> Root Mean Squared Error</a></li>
  </ul></li>
  <li><a href="#step-3-iterate-and-compare-models" id="toc-step-3-iterate-and-compare-models" class="nav-link" data-scroll-target="#step-3-iterate-and-compare-models"><span class="header-section-number">8.5</span> Step 3: Iterate and Compare Models</a>
  <ul>
  <li><a href="#regression-with-multiple-predictors" id="toc-regression-with-multiple-predictors" class="nav-link" data-scroll-target="#regression-with-multiple-predictors"><span class="header-section-number">8.5.1</span> Regression with Multiple Predictors</a></li>
  </ul></li>
  <li><a href="#application-predicting-campaign-donations" id="toc-application-predicting-campaign-donations" class="nav-link" data-scroll-target="#application-predicting-campaign-donations"><span class="header-section-number">8.6</span> Application: Predicting Campaign Donations</a>
  <ul>
  <li><a href="#visualizing-the-results" id="toc-visualizing-the-results" class="nav-link" data-scroll-target="#visualizing-the-results"><span class="header-section-number">8.6.1</span> Visualizing the results</a></li>
  <li><a href="#step-1-calculate-predictions" id="toc-step-1-calculate-predictions" class="nav-link" data-scroll-target="#step-1-calculate-predictions"><span class="header-section-number">8.6.2</span> Step 1: Calculate Predictions</a></li>
  <li><a href="#step-2-check-accuracy" id="toc-step-2-check-accuracy" class="nav-link" data-scroll-target="#step-2-check-accuracy"><span class="header-section-number">8.6.3</span> Step 2: Check Accuracy</a></li>
  <li><a href="#step-3-iterate" id="toc-step-3-iterate" class="nav-link" data-scroll-target="#step-3-iterate"><span class="header-section-number">8.6.4</span> Step 3: Iterate</a></li>
  <li><a href="#adding-model-predictors" id="toc-adding-model-predictors" class="nav-link" data-scroll-target="#adding-model-predictors"><span class="header-section-number">8.6.5</span> Adding Model Predictors</a></li>
  </ul></li>
  <li><a href="#uncertainty-with-prediction" id="toc-uncertainty-with-prediction" class="nav-link" data-scroll-target="#uncertainty-with-prediction"><span class="header-section-number">8.7</span> Uncertainty with Prediction</a>
  <ul>
  <li><a href="#example-butterfly-ballot-in-florida" id="toc-example-butterfly-ballot-in-florida" class="nav-link" data-scroll-target="#example-butterfly-ballot-in-florida"><span class="header-section-number">8.7.1</span> Example: Butterfly Ballot in Florida</a></li>
  <li><a href="#multiple-predictors" id="toc-multiple-predictors" class="nav-link" data-scroll-target="#multiple-predictors"><span class="header-section-number">8.7.2</span> Multiple Predictors</a></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals"><span class="header-section-number">8.7.3</span> Confidence Intervals</a></li>
  </ul></li>
  <li><a href="#cross-validation" id="toc-cross-validation" class="nav-link" data-scroll-target="#cross-validation"><span class="header-section-number">8.8</span> Cross-Validation</a>
  <ul>
  <li><a href="#cross-validation-process" id="toc-cross-validation-process" class="nav-link" data-scroll-target="#cross-validation-process"><span class="header-section-number">8.8.1</span> Cross-Validation Process</a></li>
  <li><a href="#application-forecasting-election-results" id="toc-application-forecasting-election-results" class="nav-link" data-scroll-target="#application-forecasting-election-results"><span class="header-section-number">8.8.2</span> Application: Forecasting Election Results</a>
  <ul class="collapse">
  <li><a href="#steps-1-and-2" id="toc-steps-1-and-2" class="nav-link" data-scroll-target="#steps-1-and-2"><span class="header-section-number">8.8.2.1</span> Steps 1 and 2</a></li>
  <li><a href="#step-3-predict-and-assess-accuracy-with-test-data" id="toc-step-3-predict-and-assess-accuracy-with-test-data" class="nav-link" data-scroll-target="#step-3-predict-and-assess-accuracy-with-test-data"><span class="header-section-number">8.8.2.2</span> Step 3: Predict and assess accuracy with test data</a></li>
  <li><a href="#step-4-repeat-process-across-all-data" id="toc-step-4-repeat-process-across-all-data" class="nav-link" data-scroll-target="#step-4-repeat-process-across-all-data"><span class="header-section-number">8.8.2.3</span> Step 4: Repeat process across all data</a></li>
  <li><a href="#step-5-summarize-performance" id="toc-step-5-summarize-performance" class="nav-link" data-scroll-target="#step-5-summarize-performance"><span class="header-section-number">8.8.2.4</span> Step 5: Summarize performance</a></li>
  <li><a href="#applying-model-to-new-data" id="toc-applying-model-to-new-data" class="nav-link" data-scroll-target="#applying-model-to-new-data"><span class="header-section-number">8.8.2.5</span> Applying Model to New Data</a></li>
  <li><a href="#challenge" id="toc-challenge" class="nav-link" data-scroll-target="#challenge"><span class="header-section-number">8.8.2.6</span> Challenge</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="regression" class="quarto-section-identifier"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Prediction with Regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>We are continuing our topic of prediction, this time adding a new tool: linear regression.</p>
<p>Recall that we predict (estimate/guess) some unknown using information we have – and do so as accurately and precisely as possible.</p>
<ol type="1">
<li>Choose an approach(es)
<ul>
<li>Using an observed (known) measure as a direct proxy to predict an outcome</li>
<li><strong><em>Using one or more observed (known) measures in a regression model to predict an outcome</em></strong></li>
<li>(Beyond the course) Using a statistical model to select the measures to use for predicting an outcome</li>
</ul></li>
<li>Assess accuracy and precision</li>
<li>Iterate to improve the prediction/classification
<ul>
<li>Often, we <a href="https://www.youtube.com/watch?v=rXPfovXw2tw">repeat steps 1-3</a> until we are confident in your method for predicting.</li>
</ul></li>
<li>Danger Zone: Eventually, after you have tested the approach and are satisfied with the accuracy, you may start applying it to new data for which you do not know the right answer.</li>
</ol>
<section id="regression-in-the-wild." class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="regression-in-the-wild."><span class="header-section-number">8.1</span> Regression in the wild.</h2>
<p>Regression is used across many domains for prediction and classification, from fantasy football to making World Cup predictions, or even predicting how far a contestant will go on <em>The Bachelor</em> or <em>The Bachelorette</em>.</p>
<p><img src="images/fantasy1.png" class="img-fluid"></p>
<p>Using data to predict reality TV outcomes.</p>
<p><img src="images/bach1.png" class="img-fluid" style="width:40.0%"> <img src="images/bachinp.png" class="img-fluid" style="width:40.0%"></p>
<p>In politics, we might use regression to build campaign models– predicting which voters are persuadable, which supporters will volunteer at campaign events, which supporters will turn out to vote, etc.</p>
<p><img src="images/polcampaign.png" class="img-fluid"></p>
</section>
<section id="application-baseball-predictions" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="application-baseball-predictions"><span class="header-section-number">8.2</span> Application: Baseball Predictions</h2>
<p>For our first example, we will stay outside of politics and use regression to predict the success of a baseball team.</p>
<p><a href="https://www.youtube.com/watch?v=-4QPVo0UIzc">Moneyball</a> is a $100 million Hollywood movie that is all about linear regression… and some baseball… and Brad Pitt, but really… it’s MOSTLY about linear regression</p>
<p><img src="images/moneyball.jpeg" class="img-fluid"></p>
<p>The movie describes the Oakland A’s shift to start using data to build their team. They make two observations 1) To win baseball games, you need runs. 2) To score runs, you need to get on base. We can estimate what on base percentage we would need as a team to score enough runs to make the playoffs in a typical season.</p>
<p>We will use regression to make these predictions.</p>
<p><em>For a video explainer of the code for this application, see below. (Via youtube, you can speed up the playback to 1.5 or 2x speed.)</em></p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/wtn-W8Uv32E" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<p>We use <code>baseball.csv</code> data</p>
<ul>
<li><code>RS</code>: runs scored;</li>
<li><code>RA</code>: runs allowed;</li>
<li><code>W</code>: wins;</li>
<li><code>Playoffs</code>: whether team made playoffs;</li>
<li><code>OBP</code>: on base percentage;</li>
<li><code>BA</code>: batting average;</li>
<li><code>SLG</code>: Slugging Percentage</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>baseball <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"baseball.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(baseball)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Team League Year  RS  RA  W   OBP   SLG    BA Playoffs RankSeason
1  ARI     NL 2012 734 688 81 0.328 0.418 0.259        0         NA
2  ATL     NL 2012 700 600 94 0.320 0.389 0.247        1          4
3  BAL     AL 2012 712 705 93 0.311 0.417 0.247        1          5
4  BOS     AL 2012 734 806 69 0.315 0.415 0.260        0         NA
5  CHC     NL 2012 613 759 61 0.302 0.378 0.240        0         NA
6  CHW     AL 2012 748 676 85 0.318 0.422 0.255        0         NA
  RankPlayoffs   G  OOBP  OSLG
1           NA 162 0.317 0.415
2            5 162 0.306 0.378
3            4 162 0.315 0.403
4           NA 162 0.331 0.428
5           NA 162 0.335 0.424
6           NA 162 0.319 0.405</code></pre>
</div>
</div>
<p>Runs scored are highly correlated with team wins.</p>
<p><img src="images/ohtani25.png" class="img-fluid"></p>
<p>What the A’s noticed is that a team’s On Base Percentage is also highly correlated with runs scored. This aligns with conventional wisdom. Players get a lot of hype when they achieve a high OBP.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/yankdodge.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>FOX 2024</figcaption>
</figure>
</div>
<p>On the 2024 world series: “The Yankees have an AL-best .347 on-base percentage… By now, it should be boilerplate: the easiest way to score runs is to put people on base. And the Yankees have scored enough to make it to the World Series.” - Jeff Passan, ESPN</p>
<p>This correlation shows up in our data, too.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08-Regression_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="step-1-approach--regression-in-r" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="step-1-approach--regression-in-r"><span class="header-section-number">8.3</span> Step 1: Approach- Regression in R</h2>
<p>A regression draws a “best fit line” between the points. This allows us – for any given OBP – to estimate the number of runs scored.</p>
<ul>
<li>Our best prediction of the number of runs scored would be the spot on the purple line directly above a given OBP.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08-Regression_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The regression model is <span class="math inline">\(Y = \alpha + \beta X + \epsilon\)</span>. Let’s demystify this. See also this interactive tutorial: https://ellaudet.iq.harvard.edu/linear_model.</p>
<ul>
<li>A regression model describes the relationship between one or more independent variables <span class="math inline">\(X\)</span> (explanatory variables) and an outcome variable <span class="math inline">\(Y\)</span> (dependent variable)
<ul>
<li>For example, the relationship between our independent variable, On Base Percentage, and our dependent variable, Runs Scored</li>
</ul></li>
<li>We want to know what happens with our dependent variable <span class="math inline">\(Y\)</span> if our independent variable <span class="math inline">\(X\)</span> increases.
<ul>
<li>As we increase our On Base Percentage, a regression model will help us estimate how much we should expect our Runs Scored to increase (or decrease) – aka rise over run aka the slope!</li>
</ul></li>
<li><span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> are considered “parameters” – things we don’t know but want to estimate. These two numbers will define exactly how we think <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are related (the shape of the line).</li>
<li>No two variables are perfectly related, so we also have the <span class="math inline">\(\epsilon\)</span> term, which describes the error in the model</li>
</ul>
<p>When we have data, we estimate <span class="math inline">\(Y\)</span>, <span class="math inline">\(\alpha\)</span>, and <span class="math inline">\(\beta\)</span>: <span class="math inline">\(\hat Y = \hat \alpha + \hat \beta X\)</span>.</p>
<ul>
<li>The <span class="math inline">\({\hat{hat}}\)</span> over the letters means those are our estimated values.</li>
</ul>
<p>In R, the regression syntax is similar to what we use in making a boxplot: <code>fit &lt;- lm(y ~ x, data = mydata)</code></p>
<ul>
<li><code>fit</code> is just whatever you want to call the output of the model,</li>
<li><code>y</code> is the name of the dependent variable,</li>
<li><code>x</code> is the name of the independent variable, and</li>
<li><code>mydata</code> is whatever you have called your dataframe. E.g.:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(RS <span class="sc">~</span> OBP, <span class="at">data =</span> baseball)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>When we have data, we estimate <span class="math inline">\(Y\)</span>, <span class="math inline">\(\alpha\)</span>, and <span class="math inline">\(\beta\)</span>: <span class="math inline">\(\hat Y = \hat \alpha + \hat \beta X\)</span>.</p>
<ul>
<li>Our model gives us the “coefficient” estimates for <span class="math inline">\(\hat \alpha\)</span> and <span class="math inline">\(\hat \beta\)</span>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         OBP 
  -1076.602    5490.386 </code></pre>
</div>
</div>
<p>The first coefficient is <span class="math inline">\(\hat \alpha\)</span>, this represents the intercept – the estimated value our dependent variable will take if our independent variable (<span class="math inline">\(x\)</span>) is 0.</p>
<ul>
<li>The value the estimated runs scored would be if a team had a 0.000 on base percentage. In our case, this value is estimated to be negative, which is impossible (but it would also be unusual for a team to have a 0.000 on base percentage). Therefore, the intercept isn’t inherently substantively interesting to us.</li>
</ul>
<p>The second coefficient is <span class="math inline">\(\hat \beta\)</span> is the slope This represents the <strong>expected change in our dependent variable for a 1-unit increase in our independent variable</strong>.</p>
<ul>
<li>For example, if we go from a 0.000 on base percentage to a 1.000 on base percentage, we would expect a 5490.4 increase in runs scored!</li>
<li>Note: slope can be positive or negative similar to correlation … BUT …</li>
<li>Note: slope is in the units of the dependent variable (e.g., runs). It is not constrained to be between -1 and 1.</li>
<li>It is telling us that the greater the OBP, the better!</li>
</ul>
<section id="visualizing-a-regression" class="level3" data-number="8.3.1">
<h3 data-number="8.3.1" class="anchored" data-anchor-id="visualizing-a-regression"><span class="header-section-number">8.3.1</span> Visualizing a regression</h3>
<p>We can plot the regression using a scatterplot and <code>abline()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>baseball<span class="sc">$</span>OBP, <span class="at">y=</span>baseball<span class="sc">$</span>RS, </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Runs Scored"</span>,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span>  <span class="st">"On Base Percentage"</span>, </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Runs Scored by On Base Percentage"</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch=</span><span class="dv">20</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Add regression line</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(fit, <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">col =</span> <span class="st">"purple"</span>) <span class="co"># add line</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08-Regression_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="making-predictions-with-regression" class="level3" data-number="8.3.2">
<h3 data-number="8.3.2" class="anchored" data-anchor-id="making-predictions-with-regression"><span class="header-section-number">8.3.2</span> Making predictions with regression</h3>
<p>A regression model allows us to estimate or “predict” values of our dependent variable for a given value of our independent variable.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08-Regression_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The red dot represents our estimate (best prediction) of the number of runs scored if a team has an on base percentage of .300. In R, we can calculate this value using <code>predict()</code>.</p>
<ul>
<li>The syntax is <code>predict(fit, data.frame(x = value))</code> where <code>fit</code> is the name of the model, <code>x</code> is the name of the independent variable, and <code>value</code> represents the value for the independent variable for which you want to predict your outcome (e.g., .300).</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fit, <span class="fu">data.frame</span>(<span class="at">OBP=</span>.<span class="dv">300</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
570.5137 </code></pre>
</div>
</div>
<p>Under the hood, this is just using the regression formula described above. For example, to estimate the number of runs scored for a .300 on base percentage, we take <span class="math inline">\(\hat \alpha + \hat \beta * .300\)</span></p>
<ul>
<li>Note that below we compare the output of the predict function to our output if we manually calculated the estimated value.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fit, <span class="fu">data.frame</span>(<span class="at">OBP=</span>.<span class="dv">300</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
570.5137 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># a + b*.300</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fit)[<span class="dv">1</span>] <span class="sc">+</span>  <span class="fu">coef</span>(fit)[<span class="dv">2</span>]<span class="sc">*</span>.<span class="dv">300</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   570.5137 </code></pre>
</div>
</div>
<p>Let’s say a team thought they needed about 900 runs scored to get to the playoffs, and they were pretty sure they could get a team on base percentage of .500. How many runs would they be expected to score with that OBP? Do you think they will make the playoffs?</p>
<details>
<summary>
Try on your own, then expand for the solution.
</summary>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fit, <span class="fu">data.frame</span>(<span class="at">OBP=</span>.<span class="dv">500</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
1668.591 </code></pre>
</div>
</div>
<p>It’s greater than 900, so we should feel good about our chances.</p>
</details>
</section>
</section>
<section id="step-2-checking-accuracy-of-model" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="step-2-checking-accuracy-of-model"><span class="header-section-number">8.4</span> Step 2: Checking accuracy of model</h2>
<p>Understanding prediction error: Where do <span class="math inline">\(\hat \alpha\)</span> and <span class="math inline">\(\hat \beta\)</span> come from? Recall that a regression tries to draw a “best fit line” between the points of data.</p>
<p>Under the hood of the regression function, we are searching for the values of <span class="math inline">\(\hat \alpha\)</span> and <span class="math inline">\(\hat \beta\)</span> that try to minimize the distance between the individual points and the regression line.</p>
<p><img src="images/residual.png" class="img-fluid" style="width:80.0%"></p>
<p>This distance is called the residual: <span class="math inline">\(\hat \epsilon_i = Y_i - \hat Y_i\)</span>.</p>
<ul>
<li>This is our <strong><em>prediction error</em></strong>: How far off our estimate of Y is (<span class="math inline">\(\hat Y_i\)</span>) from the true value of Y (<span class="math inline">\(Y_i\)</span>)</li>
<li>Linear regressions choose <span class="math inline">\(\hat \alpha\)</span> and <span class="math inline">\(\hat \beta\)</span> to minimize the “squared distance” of this error (think of this as the magnitude of the distance). This is why we tend to call this type of linear regression ordinary least squares (OLS regression).</li>
</ul>
<p>If instead we chose the red line in the image below to be the regression line, you can see that the typical prediction error would be much larger. That’s why we end up with the purple line.</p>
<p><img src="images/bestfit.png" class="img-fluid" style="width:80.0%"></p>
<section id="root-mean-squared-error" class="level3" data-number="8.4.1">
<h3 data-number="8.4.1" class="anchored" data-anchor-id="root-mean-squared-error"><span class="header-section-number">8.4.1</span> Root Mean Squared Error</h3>
<p>Just like we had root mean squared error in our poll predictions, we can calculate this for our regression.</p>
<ul>
<li>Just like with the polls, this is the square root of the mean of our squared prediction errors, or “residuals” in the case of regression.
<ul>
<li>R will give us this output using this formula where <code>fit</code> is the hypothetical name we have provided for the regression model: <code>sqrt(mean(fit$residuals^2))</code></li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>(fit<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 39.78956</code></pre>
</div>
</div>
<ul>
<li>In our case, using on based percentage to predict runs scored, our estimates are off typically, by about 40 runs scored.</li>
<li>On the graph, this means that the typical distance between a black point and the purple line is about 40.</li>
</ul>
</section>
</section>
<section id="step-3-iterate-and-compare-models" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="step-3-iterate-and-compare-models"><span class="header-section-number">8.5</span> Step 3: Iterate and Compare Models</h2>
<p>When building predictive models, often researchers want to minimize this Root-Mean Squared Error – minimizing the magnitude of the typical prediction error (the distance between the actual value of our outcome, and the true value)</p>
<p>Example: Let’s compare the RMSE from two different models:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Predicting Runs Scored with OBP</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(RS <span class="sc">~</span> OBP, <span class="at">data =</span> baseball)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Predicting Runs Scored with Batting Average</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(RS <span class="sc">~</span> BA, <span class="at">data =</span> baseball)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The Oakland A’s noticed that OBP was a more precise predictor than BA, and RMSE gives us one way to assess this.</p>
<section id="regression-with-multiple-predictors" class="level3" data-number="8.5.1">
<h3 data-number="8.5.1" class="anchored" data-anchor-id="regression-with-multiple-predictors"><span class="header-section-number">8.5.1</span> Regression with Multiple Predictors</h3>
<p>You can also add more than 1 predictor to a regression using the <code>+</code> sign.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Predicting Runs Scored with OBP and Slugging Percentage</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>fit3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(RS <span class="sc">~</span> OBP <span class="sc">+</span> SLG, <span class="at">data =</span> baseball)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>(fit3<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 25.09135</code></pre>
</div>
</div>
<p>Look how the RMSE dropped again, improving our prediction.</p>
</section>
</section>
<section id="application-predicting-campaign-donations" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="application-predicting-campaign-donations"><span class="header-section-number">8.6</span> Application: Predicting Campaign Donations</h2>
<p>Can we predict campaign donations?</p>
<p><img src="images/moneymoney.jpeg" class="img-fluid"></p>
<p>Data from Barber, Michael J., Brandice Canes‐Wrone, and Sharece Thrower. “Ideologically sophisticated donors: Which candidates do individual contributors finance?.” American Journal of Political Science 61.2 (2017): 271-288</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"donationdata.RData"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Variables</p>
<ul>
<li><code>donation</code>: 1=made donation to senator, 0=no donation made</li>
<li><code>total_donation</code>: Dollar amount of donation made by donor to Senator</li>
<li><code>sameparty</code>: 1=self-identifies as being in the candidate’s party; 0 otherwise</li>
<li><code>NetWorth</code>: Donor’s net worth. 1=less than 250k, 2=250-500k; 3=500k-1m; 4=1-2.5m; 5=2.5-5m; 6=5-10m; 7=more than 10m</li>
<li><code>IncomeLastYear</code>: Donor’s household annual income in 2013. 1=less than 50k; 2=50-100k; 3=100-125k; 4=125-150k; 5=150-250k; 6=250-300k; 7=300-350k; 8=350-400k; 9=400-500k; 10=more than 500k</li>
<li><code>peragsen</code>: percent issue agreement between donor and senator</li>
<li><code>per2agchal</code>: percent issue agreement between donor and the senator’s challenger</li>
<li><code>cook</code>: Cook competitiveness score for the senator’s race. 1 = Solid Dem or Solid Rep; 2 = Likely</li>
<li><code>matchcommf</code>: 1=Senator committee matches donor’s profession as reported in FEC file; 0=otherwise</li>
<li><code>Edsum</code>: Donor’s self-described educational attainment. 1=less than high school; 2=high school; 3=some college; 4=2-year college degree; 5=4-year college degree; 6=graduate degree</li>
</ul>
<p>Data represent information on past donors to campaigns across different states. The key dependent variable that we want to predict is <code>total_donation</code>: the total dollar amount a particular person in the data gave to their senator in the 2012 election campaign.</p>
<p>Can we predict how much someone donates to a U.S. Senate campaign?</p>
<ol type="1">
<li>Choose approach: regression of donations on donor characteristics</li>
<li>Check accuracy: calculate root-mean-squared error</li>
<li>Iterate: try different regression model specifications</li>
</ol>
<p>Let’s try a prediction based on a person’s income.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(total_donation <span class="sc">~</span> IncomeLastYear, <span class="at">data =</span> donationdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>From this, we can</p>
<ul>
<li>Plot the relationship</li>
<li>Make specific predictions at different levels of income</li>
<li>Check accuracy by calculating the prediction errors and RMSE</li>
</ul>
<section id="visualizing-the-results" class="level3" data-number="8.6.1">
<h3 data-number="8.6.1" class="anchored" data-anchor-id="visualizing-the-results"><span class="header-section-number">8.6.1</span> Visualizing the results</h3>
<p>Note that the correlation is a bit weaker here.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>donationdata<span class="sc">$</span>IncomeLastYear, </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">y=</span>donationdata<span class="sc">$</span>total_donation,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span> <span class="st">"Total Donation ($)"</span>,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Income Last Year"</span>,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Predicting Total Donations Using Income"</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(fit, <span class="at">col=</span><span class="st">"green4"</span>, <span class="at">lwd=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08-Regression_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="step-1-calculate-predictions" class="level3" data-number="8.6.2">
<h3 data-number="8.6.2" class="anchored" data-anchor-id="step-1-calculate-predictions"><span class="header-section-number">8.6.2</span> Step 1: Calculate Predictions</h3>
<p>We can calculate predictions based on a level of income. Example: Level 5 of income represents an income of $150k-250k. What level of donation would we expect?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fit, <span class="fu">data.frame</span>(<span class="at">IncomeLastYear =</span> <span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
348.8581 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="do">## alternative using coef()</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fit)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(fit)[<span class="st">"IncomeLastYear"</span>]<span class="sc">*</span><span class="dv">5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   348.8581 </code></pre>
</div>
</div>
</section>
<section id="step-2-check-accuracy" class="level3" data-number="8.6.3">
<h3 data-number="8.6.3" class="anchored" data-anchor-id="step-2-check-accuracy"><span class="header-section-number">8.6.3</span> Step 2: Check Accuracy</h3>
<p>We can calculate the Root Mean Squared Error</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>(fit<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 914.5273</code></pre>
</div>
</div>
</section>
<section id="step-3-iterate" class="level3" data-number="8.6.4">
<h3 data-number="8.6.4" class="anchored" data-anchor-id="step-3-iterate"><span class="header-section-number">8.6.4</span> Step 3: Iterate</h3>
<p>YOUR TURN: Change the model and see if it improves the prediction using RMSE using <code>sqrt(mean(fit$residuals^2))</code>.</p>
</section>
<section id="adding-model-predictors" class="level3" data-number="8.6.5">
<h3 data-number="8.6.5" class="anchored" data-anchor-id="adding-model-predictors"><span class="header-section-number">8.6.5</span> Adding Model Predictors</h3>
<p>New Model Example</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>fitnew <span class="ot">&lt;-</span> <span class="fu">lm</span>(total_donation <span class="sc">~</span> IncomeLastYear <span class="sc">+</span> NetWorth <span class="sc">+</span> sameparty, </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data=</span>donationdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>New Predictions: note how we add more variables</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fitnew, <span class="fu">data.frame</span>(<span class="at">IncomeLastYear =</span> <span class="dv">5</span>, <span class="at">NetWorth =</span> <span class="dv">4</span>, <span class="at">sameparty =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
406.9705 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="do">## alternative using coef()</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fitnew)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(fitnew)[<span class="st">"IncomeLastYear"</span>]<span class="sc">*</span><span class="dv">5</span> <span class="sc">+</span> </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>(fitnew)[<span class="st">"NetWorth"</span>]<span class="sc">*</span><span class="dv">4</span> <span class="sc">+</span> <span class="fu">coef</span>(fitnew)[<span class="st">"sameparty"</span>]<span class="sc">*</span><span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   406.9705 </code></pre>
</div>
</div>
<p>Root Mean Squared Error</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>(fitnew<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 908.9817</code></pre>
</div>
</div>
<p>When we have multiple predictors, this changes our interpretation of the coefficients slightly.</p>
<ul>
<li>We now interpret the slope as the change in the outcome expected with a 1-unit change in the independent variable– holding all other variables constant (or ``controlling” for all other variables)</li>
<li>For example, for a 1-unit change in Income, we would expect about a $68 increase in estimated donations, holding constant Net Worth and whether the person shared partisanship with the senator.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fitnew)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept) IncomeLastYear       NetWorth      sameparty 
    -242.02780       67.96825       29.55847      190.92323 </code></pre>
</div>
</div>
<p>Think of this like a set of light switches. How does adjusting one light switch affect the light in the room– holding constant all other switches.</p>
<p><img src="images/lightswitch.jpeg" class="img-fluid" style="width:60.0%"></p>
<p>When we make predictions with multiple variables, we have to tell R where we want to set each variable’s value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fitnew, <span class="fu">data.frame</span>(<span class="at">IncomeLastYear =</span> <span class="dv">5</span>, <span class="at">NetWorth =</span> <span class="dv">4</span>, <span class="at">sameparty =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
406.9705 </code></pre>
</div>
</div>
<p>See how the prediction changes if you shift <code>IncomeLastYear</code> but keep Net Worth and partisanship where they are. That’s the idea of “controlling” for the other variables!</p>
<p>How could we keep improving the predictions?</p>
<p>Eventually, we would want to apply this prediction model in a real-world setting.</p>
<ul>
<li>How could campaigns use these types of prediction models?</li>
</ul>
</section>
</section>
<section id="uncertainty-with-prediction" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="uncertainty-with-prediction"><span class="header-section-number">8.7</span> Uncertainty with Prediction</h2>
<p>Regression (and other prediction algorithms) give us our best guess</p>
<ul>
<li>But any guess has some uncertainty, prediction error, and potential outliers</li>
<li>Sometimes these errors can be systematic</li>
<li>Even when we use more advanced statistical models</li>
<li>A “best guess” is often better than a random guess– but shouldn’t necessarily be treated as “ground truth.”</li>
</ul>
<p>Prediction helps us guess unknowns with observed data, but MUST PROCEED WITH CAUTION</p>
<section id="example-butterfly-ballot-in-florida" class="level3" data-number="8.7.1">
<h3 data-number="8.7.1" class="anchored" data-anchor-id="example-butterfly-ballot-in-florida"><span class="header-section-number">8.7.1</span> Example: Butterfly Ballot in Florida</h3>
<p>In the U.S. 2000 presidential election, the race came down to Florida, which was extremely close. As part of the contest, different counties in Florida came under a microscope. One result that seemed unusual was the amount of votes Buchanan received in certain areas, which seemed to be a result of an odd ballot design choice. In this exercise, we examine voting patterns in Florida during the 2000 election.</p>
<p><img src="images/chad.jpg" class="img-fluid"></p>
<p>For more on the 2000 race, you can watch this <a href="https://www.youtube.com/watch?v=D-nR_hmS6V0&amp;ab_channel=HISTORY">video</a>.</p>
<p>Load the data and explore the variables</p>
<ul>
<li><code>county</code>: county name</li>
<li><code>Clinton96</code>: Clinton’s votes in 1996</li>
<li><code>Dole96</code>: Dole’s votes in 1996</li>
<li><code>Perot96</code>: Perot’s votes in 1996</li>
<li><code>Bush00</code>: Bush’s votes in 2000</li>
<li><code>Gore00</code>: Gore’s votes in 2000</li>
<li><code>Buchanan00</code>: Buchanan’s votes in 2000</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>florida <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"florida.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Chapter 4 in QSS also discusses this example.</p>
<p>Using what you learned from the last section, try to complete the following steps:</p>
<ul>
<li>Regress Buchanan 2000 votes (your Y) on Perot 1996 (your X) votes</li>
<li>Create a scatterplot of the two variables and add the regression line</li>
<li>Find and interpret the slope coefficient for the relationship between Perot and Buchanan votes</li>
<li>Calculate the root-mean-squared error for the regression and interpret this</li>
</ul>
<details>
<summary>
Try on your own, then expand for the solution.
</summary>
<p>For every 1 additional vote Perot received in 1996, we expect Buchanan to receive .036 additional votes in 2000.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(Buchanan00 <span class="sc">~</span> Perot96, <span class="at">data =</span> florida)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)     Perot96 
 1.34575212  0.03591504 </code></pre>
</div>
</div>
<p>In 1996, Perot received 8 million votes as a third-party candidate. Buchanan received less than 1/2 a million. Overall Perot received more votes, but where Perot received votes in 1996 was positively correlated with where Buchanan received votes in 2000.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>florida<span class="sc">$</span>Perot96,</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">y=</span>florida<span class="sc">$</span>Buchanan00,</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Buchanan Votes 2000"</span>,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Perot Votes 1996"</span>,  </span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch=</span><span class="dv">20</span>)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(fit, <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">col=</span><span class="st">"purple"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08-Regression_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>(fit<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 311.6187</code></pre>
</div>
</div>
<p>A typical prediction error is about 316.4 votes above or below the Buchanan total.</p>
</details>
</section>
<section id="multiple-predictors" class="level3" data-number="8.7.2">
<h3 data-number="8.7.2" class="anchored" data-anchor-id="multiple-predictors"><span class="header-section-number">8.7.2</span> Multiple Predictors</h3>
<p>Can we reduce the error by adding more variables?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>fitnew <span class="ot">&lt;-</span> <span class="fu">lm</span>(Buchanan00 <span class="sc">~</span> Perot96 <span class="sc">+</span> Dole96 <span class="sc">+</span> Clinton96, <span class="at">data =</span> florida)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fitnew)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)      Perot96       Dole96    Clinton96 
20.572650070  0.030663207 -0.001559196  0.001865809 </code></pre>
</div>
</div>
<p>Again, when we have multiple predictors, this changes our interpretation of the coefficients slightly.</p>
<ul>
<li>We now interpret the slope as the change in the outcome expected with a 1-unit change in the independent variable– holding all other variables constant (or ``controlling” for all other variables)</li>
<li>For example, a 1-unit increase (a 1-vote increase) in the number of Perot voters in 1996 is associated with a 0.03 vote increase in the number of Buchanan votes in 2000, holding constant the number of Clinton and Dole votes a county received.</li>
</ul>
<p>When we make predictions with multiple variables, we have to tell R where we want to set each variable’s value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fitnew, <span class="fu">data.frame</span>(<span class="at">Perot96=</span><span class="dv">20000</span>, <span class="at">Clinton96=</span><span class="dv">300000</span>, <span class="at">Dole96=</span><span class="dv">300000</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
725.8208 </code></pre>
</div>
</div>
<p>See how the prediction changes if you shift <code>Perot96</code> but keep the other variables where they are. That’s the idea of “controlling” for the other variables!</p>
<p>The addition of the new variables, in this case, made very little difference in the RMSE.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>(fit<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 311.6187</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>(fitnew<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 308.7296</code></pre>
</div>
</div>
<p>With little change from the addition of predictors, let’s stick with the more simple model and explore the prediction errors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span><span class="fu">fitted</span>(fit), <span class="co"># predicted outcome</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">y=</span><span class="fu">resid</span>(fit),  <span class="co"># prediction error</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">type=</span><span class="st">"n"</span>, <span class="co"># makes the plot blank</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1500</span>), </span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">750</span>, <span class="dv">2500</span>), </span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Predicted Buchanan Votes"</span>, </span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Prediction Error"</span>)</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>) <span class="co"># adds horizontal line</span></span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x=</span><span class="fu">fitted</span>(fit), <span class="at">y=</span><span class="fu">resid</span>(fit), <span class="at">labels =</span> florida<span class="sc">$</span>county, <span class="at">cex=</span>.<span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08-Regression_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>How does the prediction error change if we remove Palm Beach County?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>florida.pb <span class="ot">&lt;-</span> <span class="fu">subset</span>(florida, <span class="at">subset =</span> (county <span class="sc">!=</span> <span class="st">"PalmBeach"</span>))</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Buchanan00 <span class="sc">~</span> Perot96, <span class="at">data =</span> florida.pb)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>(fit2<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 86.41017</code></pre>
</div>
</div>
<p>My, oh my, our RMSE also goes way down if we remove Palm Beach. Something unique seems to be happening in that county. See this <a href="http://sekhon.berkeley.edu/papers/butterfly.pdf">academic paper</a> for an elaboration of the evidence that “The Butterfly [ballot] Did it.”</p>
</section>
<section id="confidence-intervals" class="level3" data-number="8.7.3">
<h3 data-number="8.7.3" class="anchored" data-anchor-id="confidence-intervals"><span class="header-section-number">8.7.3</span> Confidence Intervals</h3>
<p>Social scientists like to characterize the uncertainty in their predictions using what is called a “confidence interval.”</p>
<ul>
<li>Confidence intervals show a range of values that are likely to contain the true value</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fit, <span class="fu">data.frame</span>(<span class="at">Perot96 =</span> <span class="dv">13600</span>), <span class="at">interval =</span> <span class="st">"confidence"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 489.7903 394.8363 584.7443</code></pre>
</div>
</div>
<p>By default, R supplies the 95% confidence interval.</p>
<ul>
<li>For example, our estimate is for a county with 13,600 votes for Perot in 1996, the expected Buchanan vote is 489.79 votes.
<ul>
<li>The confidence interval is 394.84 to 584.74 votes, which means we believe there is a 95% chance that this interval contains the true value of the Buchanan 2000 vote share.</li>
</ul></li>
<li>Instead of thinking about our prediction as just 489.79, we should think about the entire interval as having a good chance of including the true value.</li>
</ul>
<p>Similarly, our coefficients also have uncertainty.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)     Perot96 
 1.34575212  0.03591504 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   2.5 %       97.5 %
(Intercept) -98.03044506 100.72194929
Perot96       0.02724733   0.04458275</code></pre>
</div>
</div>
<p>For every 1 vote increase in the Perot 1996 vote, we expect a <span class="math inline">\(\hat \beta =.036\)</span> increase in Buchanan votes. However, the confidence interval is 0.027 to 0.045.</p>
<ul>
<li>We think there is a 95% chance that this interval 0.027 to 0.045 includes the true <span class="math inline">\(\beta\)</span>, describing the rate of change in Buchanan votes for a given change in Perot 1996 votes</li>
</ul>
</section>
</section>
<section id="cross-validation" class="level2" data-number="8.8">
<h2 data-number="8.8" class="anchored" data-anchor-id="cross-validation"><span class="header-section-number">8.8</span> Cross-Validation</h2>
<p>So far, we’ve been “cheating.” We’ve been analyzing a prediction in cases where we know the right answer. Now we will focus more squarely on how to develop an “out-of-sample” prediction.</p>
<p>Problem: Models that fit our existing (“in-sample”) data might not be the best for predicting out-of-sample data.</p>
<p>Example: Compare regression line with vs.&nbsp;without Palm Beach included in the sample.</p>
<ul>
<li>Outliers “in-sample” can lead to overfitting to weird, idiosyncratic data points</li>
</ul>
<p><img src="images/overfit.png" class="img-fluid"></p>
<p>Example: Error Rates in Speech Recognition. See study <a href="https://news.stanford.edu/2020/03/23/automated-speech-recognition-less-accurate-blacks/">here</a></p>
<ul>
<li>Predictions/Classification that works well for one group might not work well for all groups</li>
</ul>
<p><img src="images/speecherrors.png" class="img-fluid"></p>
<p>Problem: Models that fit our existing (“in-sample”) data might not be the best for predicting out-of-sample data. Approaches to diagnose the problem or help address it:</p>
<ul>
<li>Detect potential outliers within existing data by exploring the prediction errors</li>
<li>Make sure the training (in-sample) data is as representative as possible</li>
<li>Incorporate out-of-sample testing in prediction process</li>
</ul>
<section id="cross-validation-process" class="level3" data-number="8.8.1">
<h3 data-number="8.8.1" class="anchored" data-anchor-id="cross-validation-process"><span class="header-section-number">8.8.1</span> Cross-Validation Process</h3>
<p>Cross-validation incorporates the idea of out-of-sample testing into the process of how we evaluate the accuracy of prediction and classification approaches.</p>
<p>Cross-validation (train vs.&nbsp;test data)</p>
<ol type="1">
<li>Subset your data into two portions: Training and Test data.</li>
<li>Run a model based on the training data.</li>
<li>Make a prediction and test the accuracy on the test data.</li>
<li>Repeat process training and testing on different portions of the data.</li>
<li>Summarize the results and choose a preferred model
<ul>
<li>Eventually: Apply this model to entirely new data</li>
</ul></li>
</ol>
<p>Goal: Test accuracy in a way that can help detect overfitting. See how well our model will generalize to new data (data the model hasn’t seen).</p>
</section>
<section id="application-forecasting-election-results" class="level3" data-number="8.8.2">
<h3 data-number="8.8.2" class="anchored" data-anchor-id="application-forecasting-election-results"><span class="header-section-number">8.8.2</span> Application: Forecasting Election Results</h3>
<p>Macro political and economic fundamentals are sometimes used for early forecasting of an election. We will build a version of this model and test its accuracy using a process of “Leave-one-out” cross-validation.</p>
<p>Below is a video explainer of a similar application, which uses cross-validation.</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/Wqj9Jm8heAA" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>fair <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"fair20.csv"</span>)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>fair <span class="ot">&lt;-</span> <span class="fu">subset</span>(fair, t <span class="sc">&gt;=</span> <span class="dv">1916</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<iframe title="Fair's presidential vote equation" aria-label="Table" id="datawrapper-chart-g7B9i" src="https://datawrapper.dwcdn.net/g7B9i/3/" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="609" data-external="1">
</iframe>
<script type="text/javascript">!function(){"use strict";window.addEventListener("message",(function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r=0;r<e.length;r++)if(e[r].contentWindow===a.source){var i=a.data["datawrapper-height"][t]+"px";e[r].style.height=i}}}))}();</script>
<p>Let’s propose a model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(VP <span class="sc">~</span>  DUR, <span class="at">data =</span> fair)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s propose an alternative model and see which one we think is better.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(VP <span class="sc">~</span> G<span class="sc">*</span>I <span class="sc">+</span> DUR , <span class="at">data =</span> fair)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note: The asterisk represents an “interaction.” See QSS Chapter 4. We use this when we think the effect of one variable (growth) may depend on the values of another variable (the party of who is in office).</p>
<section id="steps-1-and-2" class="level4" data-number="8.8.2.1">
<h4 data-number="8.8.2.1" class="anchored" data-anchor-id="steps-1-and-2"><span class="header-section-number">8.8.2.1</span> Steps 1 and 2</h4>
<p>We are going to run a model where each time we `leave out’ one row of data (in our case, one election). Let’s try this once:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(fair<span class="sc">$</span>t)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1916 2020</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Step 1: Subset data into two portions</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>traindata <span class="ot">&lt;-</span> fair[<span class="sc">-</span><span class="dv">1</span>,]</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>testdata <span class="ot">&lt;-</span> fair[<span class="dv">1</span>,]</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Step 2: Run model on training data</span></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(VP <span class="sc">~</span>  DUR, <span class="at">data =</span> traindata)</span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(VP <span class="sc">~</span>  G<span class="sc">*</span>I <span class="sc">+</span> DUR , <span class="at">data =</span> traindata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="step-3-predict-and-assess-accuracy-with-test-data" class="level4" data-number="8.8.2.2">
<h4 data-number="8.8.2.2" class="anchored" data-anchor-id="step-3-predict-and-assess-accuracy-with-test-data"><span class="header-section-number">8.8.2.2</span> Step 3: Predict and assess accuracy with test data</h4>
<p>Out-of-Sample prediction</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Step 3: Make a Prediction using test data and</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>yhat.fit <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit, testdata)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>yhat.fit2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit2, testdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Prediction error (Truth - Prediction)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Step 3: Test accuracy of prediction</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>error.fit <span class="ot">&lt;-</span> testdata<span class="sc">$</span>VP <span class="sc">-</span> yhat.fit</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>error.fit2 <span class="ot">&lt;-</span> testdata<span class="sc">$</span>VP <span class="sc">-</span> yhat.fit2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="step-4-repeat-process-across-all-data" class="level4" data-number="8.8.2.3">
<h4 data-number="8.8.2.3" class="anchored" data-anchor-id="step-4-repeat-process-across-all-data"><span class="header-section-number">8.8.2.3</span> Step 4: Repeat process across all data</h4>
<p>Step 4: Let’s do this for each row, storing the prediction errors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Iteration vector</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="do">## just i!</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Empty container vectors</span></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>errors.fit <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="fu">nrow</span>(fair))</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>errors.fit2 <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="fu">nrow</span>(fair))</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Loop (copy paste meat from  above)</span></span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span>  <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(fair)){</span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>  traindata <span class="ot">&lt;-</span> fair[<span class="sc">-</span>i,]</span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a>  testdata <span class="ot">&lt;-</span> fair[i,]</span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>  fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(VP <span class="sc">~</span> DUR, <span class="at">data =</span> traindata)</span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>  fit2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(VP <span class="sc">~</span> G<span class="sc">*</span>I <span class="sc">+</span> DUR   , <span class="at">data =</span> traindata)</span>
<span id="cb72-13"><a href="#cb72-13" aria-hidden="true" tabindex="-1"></a>  yhat.fit <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit, testdata)</span>
<span id="cb72-14"><a href="#cb72-14" aria-hidden="true" tabindex="-1"></a>  yhat.fit2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit2, testdata)</span>
<span id="cb72-15"><a href="#cb72-15" aria-hidden="true" tabindex="-1"></a>  errors.fit[i] <span class="ot">&lt;-</span> testdata<span class="sc">$</span>VP <span class="sc">-</span> yhat.fit</span>
<span id="cb72-16"><a href="#cb72-16" aria-hidden="true" tabindex="-1"></a>  errors.fit2[i] <span class="ot">&lt;-</span> testdata<span class="sc">$</span>VP <span class="sc">-</span> yhat.fit2</span>
<span id="cb72-17"><a href="#cb72-17" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="step-5-summarize-performance" class="level4" data-number="8.8.2.4">
<h4 data-number="8.8.2.4" class="anchored" data-anchor-id="step-5-summarize-performance"><span class="header-section-number">8.8.2.4</span> Step 5: Summarize performance</h4>
<p>Step 5: Summarize the model performance</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="do">## RMSE</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>((errors.fit)<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.907188</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>((errors.fit2)<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.794056</code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Mean Absolute Error</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">abs</span>(errors.fit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.633719</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">abs</span>(errors.fit2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.332114</code></pre>
</div>
</div>
<p>Which model tends to have less error?</p>
</section>
<section id="applying-model-to-new-data" class="level4" data-number="8.8.2.5">
<h4 data-number="8.8.2.5" class="anchored" data-anchor-id="applying-model-to-new-data"><span class="header-section-number">8.8.2.5</span> Applying Model to New Data</h4>
<p>Eventually, you might further test the model on data that has been “held out”– data that neither your train/test has seen. How good was our model? We can do this for the 2024 election, which was not in the data.</p>
<p>Truth: 2024 VP was Democratic “two-party” vote share.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Let's use the winner of our two models</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(VP <span class="sc">~</span> G<span class="sc">*</span>I <span class="sc">+</span> DUR, <span class="at">data =</span> fair)</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>prediction24 <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit2, <span class="fu">data.frame</span>(<span class="at">G=</span><span class="fl">1.97</span>, <span class="at">I=</span><span class="dv">0</span>, <span class="at">DUR=</span><span class="dv">0</span>,</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">P=</span> <span class="fl">4.54</span>, <span class="at">Z=</span> <span class="dv">4</span>, <span class="at">WAR=</span><span class="dv">0</span>))</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>prediction24</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
49.13402 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>predictionerror <span class="ot">&lt;-</span> <span class="fl">49.2</span> <span class="sc">-</span> prediction24</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>predictionerror</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1 
0.06598466 </code></pre>
</div>
</div>
<p>2024 values based on the FAIR <a href="https://fairmodel.econ.yale.edu/vote2020/computv4.htm">site</a></p>
</section>
<section id="challenge" class="level4" data-number="8.8.2.6">
<h4 data-number="8.8.2.6" class="anchored" data-anchor-id="challenge"><span class="header-section-number">8.8.2.6</span> Challenge</h4>
<p>Can you build a better model? Would you have treated “I” differently or used different values for the other variables? What would your prediction for 2024 have been? What about other years?</p>
<ul>
<li>G=1.97</li>
<li>P= 4.54</li>
<li>Z= 4</li>
<li>I= 0</li>
<li>DUR = 0</li>
</ul>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./07-Prediction.html" class="pagination-link" aria-label="Prediction">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Prediction</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./09-Fairness.html" class="pagination-link" aria-label="Fairness and Ethics">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Fairness and Ethics</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>